### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by anywhichway** [scicave/rakam#4]
I have installed your NPM package and tried running `npm install` in the node-modules/rakam directory. I have also cloned your repository and tried an install. Both fail. I have also tried `npm run build` in both places and it fails.

In node-modules/rakam:

```
npm install
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> rakam@1.0.0-1 prepare /home/syblackwell/git/downrunner/node_modules/rakam
> npm run lint && npm run test


> rakam@1.0.0-1 lint /home/syblackwell/git/downrunner/node_modules/rakam
> eslint src/ --fix


Oops! Something went wrong! :(

ESLint: 7.9.0

No files matching the pattern "src/" were found.
Please check for typing mistakes in the pattern.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! rakam@1.0.0-1 lint: `eslint src/ --fix`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the rakam@1.0.0-1 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/syblackwell/.npm/_logs/2020-09-25T17_55_48_943Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! rakam@1.0.0-1 prepare: `npm run lint && npm run test`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the rakam@1.0.0-1 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/syblackwell/.npm/_logs/2020-09-25T17_55_49_086Z-debug.log
```

In /rakam:

```
npm install

> rakam@1.0.0-1 prepare /home/syblackwell/git/rakam
> npm run lint && npm run test


> rakam@1.0.0-1 lint /home/syblackwell/git/rakam
> eslint src/ --fix


> rakam@1.0.0-1 test /home/syblackwell/git/rakam
> jest

 FAIL  test/geometry/angles.test.js
  ● Test suite failed to run

    Configuration error:
    
    Could not locate module rakam mapped as:
    /home/syblackwell/git/rakam/main/index.js.
    
    Please check your configuration for these entries:
    {
      "moduleNameMapper": {
        "/rakam/": "/home/syblackwell/git/rakam/main/index.js"
      },
      "resolver": undefined
    }

    > 1 | const { angles, vector } = require('rakam');
        |                            ^
      2 | 
      3 | // the acceptable differencve between the expected
      4 | // value and the return angle from "angles" methods

      at createNoMappedModuleFoundError (node_modules/jest-resolve/build/index.js:552:17)
      at Object.<anonymous> (test/geometry/angles.test.js:1:28)

 FAIL  test/fraction/fraction.test.js
  ● Test suite failed to run

    Configuration error:
    
    Could not locate module rakam mapped as:
    /home/syblackwell/git/rakam/main/index.js.
    
    Please check your configuration for these entries:
    {
      "moduleNameMapper": {
        "/rakam/": "/home/syblackwell/git/rakam/main/index.js"
      },
      "resolver": undefined
    }

    > 1 | const {quotRem, frac, randomInt, random } = require('rakam');
        |                                             ^
      2 | 
      3 | let tests = [
      4 |   {

      at createNoMappedModuleFoundError (node_modules/jest-resolve/build/index.js:552:17)
      at Object.<anonymous> (test/fraction/fraction.test.js:1:45)

 FAIL  test/engine/math2js.test.js
  ● Test suite failed to run

    Configuration error:
    
    Could not locate module rakam mapped as:
    /home/syblackwell/git/rakam/main/index.js.
    
    Please check your configuration for these entries:
    {
      "moduleNameMapper": {
        "/rakam/": "/home/syblackwell/git/rakam/main/index.js"
      },
      "resolver": undefined
    }

      2 | 
      3 | // we are using rollup-jest transformer
    > 4 | const {math2js} = require('rakam');
        |                   ^
      5 | const defaultHandlers = math2js.defaultHandlers;
      6 | const generateJs = math2js.generateJs;
      7 | 

      at createNoMappedModuleFoundError (node_modules/jest-resolve/build/index.js:552:17)
      at Object.<anonymous> (test/engine/math2js.test.js:4:19)

Test Suites: 3 failed, 3 total
Tests:       0 total
Snapshots:   0 total
Time:        2.443 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rakam@1.0.0-1 test: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rakam@1.0.0-1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/syblackwell/.npm/_logs/2020-09-25T17_43_31_829Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rakam@1.0.0-1 prepare: `npm run lint && npm run test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rakam@1.0.0-1 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/syblackwell/.npm/_logs/2020-09-25T17_43_31_953Z-debug.log
```

**Comment by ms2052001** [comment]
I am so sad for my delay, I really would pay attention to the people wanting to accomplish their projects easily and quickly. I hope you have found a solution for your project.
For this issue: you ware testing the installed node module, you should use that package directly with the `require` function or with ES6's `import`, and a bundler to get your script ready for the browser.
You have corrected your mistake and cloned the git repo to do `lint` and `test` tesks. But you would have `build` first.

**Comment by ms2052001** [comment]
I have just noticed my silly bug in `package.json`, the task `prepare` runs before executing `install`. So the test is done before building, the bundled file `./main/index.js` is required by the test files.
